---
- name: Add ppa Repository (php)
  sudo: yes
  apt_repository: repo=ppa:ondrej/php5-5.6 update_cache=yes

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - libapache2-mod-fastcgi
    - php5-cgi
    - php5-cli
    - php5-common
    - php5-curl
    - php5-fpm
    - php5-gd
    - php5-imagick
    - php5-intl
    - php5-mcrypt
    - php5-mysql
    - php5-readline
    - php5-sqlite
    - php5-xdebug
    - php5-xsl
    - php5-json

- name: Configure PHP-FPM to use UNIX sockets instead of TCP
  sudo: yes
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf
              regexp='listen = '
              line='listen = /var/run/php5-fpm.sock'

- name: ensure timezone is set in fpm php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'

- name: ensure timezone is set in cgi php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'

- name: ensure timezone is set in cli php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'

- name: ensure max_execution_time is set in fpm php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp='max_execution_time ='
              line='max_execution_time = 900'

- name: ensure max_execution_time is set in cgi php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini
              regexp='max_execution_time ='
              line='max_execution_time = 900'

- name: ensure memory_limit is set in fpm php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp='memory_limit ='
              line='memory_limit = 512M'

- name: ensure memory_limit is set in cli php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='memory_limit ='
              line='memory_limit = 512M'

- name: ensure realpath_cache_size is set in fpm php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp='realpath_cache_size ='
              line='realpath_cache_size = 4096k'

- name: ensure realpath_cache_size is set in cli php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='realpath_cache_size ='
              line='realpath_cache_size = 4096k'

- name: ensure realpath_cache_size is set in cgi php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini
              regexp='realpath_cache_size ='
              line='realpath_cache_size = 4096k'

- name: ensure realpath_cache_ttl is set in fpm php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp='realpath_cache_ttl ='
              line='realpath_cache_ttl = 7200'

- name: ensure realpath_cache_ttl is set in cli php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='realpath_cache_ttl ='
              line='realpath_cache_ttl = 7200'

- name: ensure realpath_cache_ttl is set in cgi php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini
              regexp='realpath_cache_ttl ='
              line='realpath_cache_ttl = 7200'

- name: set SYMFONY_ENV variable
  sudo: yes
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf
            section=www
            option='env[SYMFONY_ENV]'
            value='prod'
  notify: restart php5-fpm

- name: Set www group to vagrant
  sudo: yes
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf
            section=www
            option=group
            value=vagrant
  notify: restart php5-fpm

- name: Set www group to vagrant
  sudo: yes
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf
            section=www
            option=user
            value=vagrant
  notify: restart php5-fpm

- name: set DEVELOPMENT env variable
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf
            section=www
            option='env[DEVELOPMENT]'
            value=true
  notify: restart php5-fpm
