---
# application tasks to be customized and to run after the main provision
- name: Setup watcher nfs cache clearing
  sudo: yes
  shell: watch -n16 "sysctl -w vm.drop_caches=3" > /dev/null &
  when: inventory_hostname == "192.168.56.128"

- name: Create tmpfs
  sudo: yes
  mount: name=/vagrant/app/cache src=none fstype=tmpfs opts="size=256m" state=mounted

- name: Composer install
  shell: cd /vagrant && composer install

# can't login as mysql user root from normal user account in ubuntu 16.04
# see:
# https://askubuntu.com/questions/766334/cant-login-as-mysql-user-root-from-normal-user-account-in-ubuntu-16-04
# https://askubuntu.com/questions/763336/cannot-enter-phpmyadmin-as-root-mysql-5-7
- name: Update root password
  sudo: yes
  shell: sudo mysql -u root --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY ''";
